[package]
name = "rust_socketio"
authors = ["Bastian Kersting <bastian@cmbt.de>"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "An implementation of a socketio client written in rust."
readme = "../README.md"
repository = "https://github.com/1c3t3a/rust-socketio"
keywords = ["socketio", "engineio", "network", "protocol", "client"]
categories = ["network-programming", "web-programming", "web-programming::websocket"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
rust_engineio = { path = "../engineio" }
base64 = { workspace = true }
bytes = { workspace = true }
backoff = "0"
rand = { version = "0", features = ["thread_rng"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
rustls = { workspace = true }
url = { workspace = true }
tokio = { workspace = true, optional = true }
futures-util = { workspace = true, default-features = false, features = ["sink"], optional = true }
async-stream = { workspace = true, optional = true }
log = "0"
serde = { workspace = true }

[dev-dependencies]
serial_test = "4"

[dev-dependencies.tokio]
workspace = true
# we need the `#[tokio::test]` macro
features = ["macros", "rt-multi-thread"]

[features]
default = []
async-callbacks = ["rust_engineio/async-callbacks"]
async = ["async-callbacks", "rust_engineio/async", "tokio", "futures-util", "async-stream"]

[[example]]
name = "async"
path = "examples/async.rs"
required-features = ["async"]

[lints]
workspace = true
