[package]
name = "rust_engineio"
authors = ["Bastian Kersting <bastian@cmbt.de>"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "An implementation of a engineio client written in rust."
readme = "README.md"
repository = "https://github.com/1c3t3a/rust-socketio"
keywords = ["engineio", "network", "protocol", "client"]
categories = ["network-programming", "web-programming", "web-programming::websocket"]
license = "MIT"

[package.metadata.docs.rs]
all-features = true

[dependencies]
base64 = { workspace = true }
bytes = { workspace = true }
reqwest = { version = "0", features = ["blocking", "rustls", "stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
http = "1"
tokio-tungstenite = { version = "0", features = ["rustls-tls-native-roots", "url"] }
tungstenite = "0"
tokio = { workspace = true, features = ["rt-multi-thread"] }
futures-util = { workspace = true, default-features = false, features = ["sink"] }
async-trait = "0"
async-stream = { workspace = true }
thiserror = { workspace = true }
rustls = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["async_tokio"] }
lazy_static = "1.4.0"

[dev-dependencies.tokio]
workspace = true
# we need the `#[tokio::test]` macro
features = ["macros"]

[[bench]]
name = "codec"
harness = false

[[bench]]
name = "engineio"
harness = false

# needs to be present in order to support the benchmark
# ci job
# source: https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[features]
default = ["async"]
async-callbacks = []
async = ["async-callbacks"]

[lints]
workspace = true
